
server:
  port: 9000

spring:
  application:
    name: user-service
  jpa:
    database: mysql
    show-sql: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tasty

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: jung
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.15:8761/eureka


mybatis:
  config-location: classpath:config/myBatis.xml

